export const clientScript = `(function(){
var timer, retry, busy=false, currentArt=null, forecast=null, offset=0, lastSlot=-1;
function el(id){return document.getElementById(id)}
function text(id,value){el(id).textContent=value}
function icon(code){var sun='<circle cx="12" cy="12" r="4"/><path d="M12 1v2m0 18v2M1 12h2m18 0h2M4 4l2 2m12 12l2 2M4 20l2-2M18 6l2-2"/>', cloud='<path d="M6 18h12a4 4 0 0 0 0-8 6 6 0 0 0-11-2 5 5 0 0 0-1 10Z"/>', rain='<path d="m8 20-1 2m6-2-1 2m6-2-1 2"/>';return '<svg aria-hidden="true" viewBox="0 0 24 24">'+(code===0?sun:cloud+(code>=51?rain:''))+'</svg>'}
function dateLabel(){var date=new Date(Date.now()+offset);try{text('date',date.toLocaleDateString('en-US',{timeZone:'America/Los_Angeles',weekday:'short',month:'short',day:'numeric'}))}catch(e){text('date',date.toDateString())}}
function showWeather(w){forecast=w;text('temperature',w.temperature);text('conditions',w.label);el('current-icon').innerHTML=icon(w.code);var html='';for(var i=0;i<w.days.length;i++){var d=w.days[i],name=i===0?'Today':new Date(d.date+'T12:00:00').toLocaleDateString('en-US',{weekday:'short'});html+='<div class="day"><div class="day-name">'+name+'</div>'+icon(d.code)+'<div class="temps">'+d.high+'°<span class="low">'+d.low+'°</span></div><div class="rain">'+(d.rain===null?'—':d.rain+'%')+' rain</div></div>'}el('days').innerHTML=html}
function tryAgain(){clearTimeout(retry);retry=setTimeout(update,60000)}
function showArt(a){if(currentArt===a.id)return;var image=new Image();image.onload=function(){el('art').src=image.src;el('art').alt=a.title+' by '+a.artist_title;el('art').style.display='block';el('placeholder').style.display='none';text('title',a.title);text('artist',a.artist_title+' · '+a.date_display);el('credit').href=a.source;currentArt=a.id};image.onerror=function(){text('status','Art unavailable · retrying shortly');tryAgain()};image.src='/api/display/art?id='+a.id}
function update(){if(busy)return;busy=true;clearTimeout(timer);clearTimeout(retry);var xhr=new XMLHttpRequest();xhr.open('GET','/api/display/content?t='+Date.now(),true);xhr.timeout=25000;xhr.onload=function(){busy=false;if(xhr.status===401){window.location.replace('/display');return}if(xhr.status!==200){failed();return}try{var data=JSON.parse(xhr.responseText);offset=data.serverTime-Date.now();lastSlot=Math.floor(data.serverTime/3600000);showArt(data.art);dateLabel();if(data.weather){showWeather(data.weather);text('status','Art & weather · updated hourly')}else{text('status',forecast?'Forecast temporarily unavailable · showing last update':'Weather unavailable · retrying shortly');tryAgain()}timer=setTimeout(update,Math.max(1000,data.nextUpdate-(Date.now()+offset)+250))}catch(e){failed()}};xhr.onerror=xhr.ontimeout=function(){busy=false;failed()};xhr.send()}
function failed(){text('status','Connection interrupted · retrying shortly');tryAgain()}
window.addEventListener('online',update);document.addEventListener('visibilitychange',function(){if(!document.hidden)update()});setInterval(function(){dateLabel();if(Math.floor((Date.now()+offset)/3600000)>lastSlot&&!busy)update()},60000);update();
})();`;
